unique_ids:
  assets:
    standard-page.html: HIGRIWW3SYMVTX2ZQSE5AJ4KQLLMYQAO
    theme.css: 2Y6H7AK6WPG4552LW6P7SDS565C7ZOSH
  forms:
    Main: XIVWKEOPK6F4MUUUSDSMYWTCSPDTML2I
    Slider: UYMHLPOFO7LQQNDSITLAEP2DA2LE3JPC
  modules:
    License: N5TWVZSAVF6FNMX6GCOCAZDVCNUSEDRG
  scripts: {}
  server_modules: {}
